#!/bin/sh

if [ $(whoami) != "root" ]; then
    echo "Please run as root or using sudo"
    exit 1
fi

apk add git
git clone https://github.com/jaclu/ish-config.git /opt/ish-config
ln -sf /opt/ish-config/ish_config.sh /usr/local/bin/ish_config
ln -sf /opt/ish-config/set-timezone.sh /usr/local/bin/set-timezone

echo
echo "you should now have ish_config and set-timezone in your path"
