#!/bin/sh
#
#  Part of https://github.com/jaclu/ish-config
#
#  Copyright (c) 2022: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  This is the auto installation script
#
if [ "$(whoami)" != "root" ]; then
    echo "Please run as root or using sudo"
    exit 1
fi

echo
echo "Installing ish-config"
echo

apk add git

git clone https://github.com/jaclu/ish-config.git /opt/ish-config

ln -sf /opt/ish-config/ish-config.sh /usr/local/bin/ish-config
ln -sf /opt/ish-config/set-timezone.sh /usr/local/bin/set-timezone

echo
echo "You should now have ish-config and set-timezone in your PATH"
